# Generated by Django 4.1 on 2022-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
